---

- name: add apt-key
  apt_key:
    id: 2980AECF
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  become: yes

- name: add virtualbox repo
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
    update_cache: yes
  become: yes

- name: install virtualbox
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - dkms
    - virtualbox-{{ vbox_major_minor_version }}
  become: yes
