---

- name: download extpack
  get_url:
    url: http://download.virtualbox.org/virtualbox/{{ vbox_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ vbox_version }}-{{ vbox_build }}.vbox-extpack
    dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ vbox_version }}-{{ vbox_build }}.vbox-extpack
    mode: 0664

- name: install extpack
  command: VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ vbox_version }}-{{ vbox_build }}.vbox-extpack --accept-license={{ vbox_accept_license }}
  become: yes
